# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"

jobs:
  check:
     if: github.event.pull_request.draft == false
     runs-on: ubuntu-latest
     steps:
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: 1.23.x
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Lint
       run: |
         rm -rf $HOME/.cache/golangci-lint
         make lint
  goimports-lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - run: goimports -local . -w .
      - run: go mod tidy
      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run Makefile check-mod-tidy
        run: make check-mod-tidy
      - name: Build
        run: make build
      - name: Build Test
        run: make build_transfer_test_race
      - name: Parallel Transfer Test
        run: make ci_parallel_transfer_test
      - name: Serial Transfer Test
        run: make ci_serial_transfer_test
      - name: Build Uniswap Test
        run: make build_uniswap_test_race
      - name: Parallel Uniswap Test
        run: make ci_parallel_uniswap_test
      - name: Serial Uniswap Test
        run: make ci_serial_uniswap_test
